apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: application
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: application
spec:
  selector:
      run: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80