apiVersion: apps/v1
kind: Pod
metadata:
  name: nginx-deployment
  namespace: application
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: application
spec:
  selector:
      app.kubernetes.io/name: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80